2018-03-11 18:21:38 cms_handlers.py[line:110] ERROR 'gt_server_status not found'
Traceback (most recent call last):
  File "/home/xiaodong/gittemp/healer_blogs_web/handler/cms/cms_handlers.py", line 38, in post
    status = int(self.session[gt.GT_STATUS_SESSION_KEY])
  File "build/bdist.linux-x86_64/egg/tornado_session/session.py", line 213, in __getitem__
    raise KeyError('%s not found' % key)
KeyError: 'gt_server_status not found'
2018-03-11 18:21:49 cms_handlers.py[line:110] ERROR 'gt_server_status not found'
Traceback (most recent call last):
  File "/home/xiaodong/gittemp/healer_blogs_web/handler/cms/cms_handlers.py", line 38, in post
    status = int(self.session[gt.GT_STATUS_SESSION_KEY])
  File "build/bdist.linux-x86_64/egg/tornado_session/session.py", line 213, in __getitem__
    raise KeyError('%s not found' % key)
KeyError: 'gt_server_status not found'
2018-03-11 18:22:08 cms_handlers.py[line:110] ERROR 'dict' object has no attribute 'haskey'
Traceback (most recent call last):
  File "/home/xiaodong/gittemp/healer_blogs_web/handler/cms/cms_handlers.py", line 102, in post
    self.clear_session_obj()
  File "build/bdist.linux-x86_64/egg/tornado_session/session.py", line 259, in clear_session_obj
    self.session_handler.driver.clear(session_id)
  File "build/bdist.linux-x86_64/egg/tornado_session/memorysession.py", line 69, in clear
    if self._data_handler.haskey(session_id):
AttributeError: 'dict' object has no attribute 'haskey'
2018-03-11 18:23:04 cms_handlers.py[line:110] ERROR 'dict' object has no attribute 'haskey'
Traceback (most recent call last):
  File "/home/xiaodong/gittemp/healer_blogs_web/handler/cms/cms_handlers.py", line 102, in post
    self.clear_session_obj()
  File "build/bdist.linux-x86_64/egg/tornado_session/session.py", line 259, in clear_session_obj
    self.session_handler.driver.clear(session_id)
  File "build/bdist.linux-x86_64/egg/tornado_session/memorysession.py", line 69, in clear
    if self._data_handler.haskey(session_id):
AttributeError: 'dict' object has no attribute 'haskey'
2018-03-11 18:24:39 web.py[line:2064] WARNING 404 GET /static/css/bootstrap.min.css.map (192.168.1.123) 6.67ms
2018-03-11 18:28:41 web.py[line:2064] WARNING 404 GET /login?next=%2Fcms%2F (192.168.1.123) 4.07ms
2018-03-11 18:28:52 web.py[line:2064] WARNING 404 GET /login?next=%2Fcms%2F (192.168.1.123) 2.20ms
2018-03-11 18:30:11 web.py[line:2064] WARNING 404 GET /login?next=%2Fcms%2F (192.168.1.123) 2.71ms
2018-03-11 18:32:25 web.py[line:2064] WARNING 404 GET /login?next=%2Fcms%2F (192.168.1.123) 1.49ms
2018-03-11 18:32:56 web.py[line:2064] WARNING 404 GET /static/css/bootstrap.min.css.map (192.168.1.123) 5.10ms
2018-03-11 18:33:00 web.py[line:1591] ERROR Uncaught exception GET /cms/logout (192.168.1.123)
HTTPServerRequest(protocol='http', host='192.168.1.182:8010', method='GET', uri='/cms/logout', version='HTTP/1.1', remote_ip='192.168.1.123', headers={'Accept-Language': 'zh-CN,zh;q=0.9', 'Accept-Encoding': 'gzip, deflate', 'Host': '192.168.1.182:8010', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.119 Safari/537.36', 'Dnt': '1', 'Connection': 'keep-alive', 'Referer': 'http://192.168.1.182:8010/cms/', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache', 'Cookie': 'sessionID=0UiAHYb3eCXKjbIs-KeOqnlnMjMIAJceQiV1f7g2; msid=e1dHKjhzacG6tIU-MdqFzFCxpY1En-tmMdW7N3jp; _xsrf=2|f7030538|7d8778473a8e1a5cdd4289802e49ec97|1520749458; user="2|1:0|10:1520764376|4:user|16:aHlwQHFxLmNvbQ==|499397512cabc459b2aa4af63885c555c76c0213c04c764a8a8fe1d9ff3e6ff7"', 'Upgrade-Insecure-Requests': '1'})
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1512, in _execute
    result = yield result
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 292, in wrapper
    result = func(*args, **kwargs)
  File "/home/xiaodong/gittemp/healer_blogs_web/handler/cms/cms_handlers.py", line 151, in get
    self.clear_session_obj()
  File "build/bdist.linux-x86_64/egg/tornado_session/session.py", line 259, in clear_session_obj
    self.session_handler.driver.clear(session_id)
  File "build/bdist.linux-x86_64/egg/tornado_session/memorysession.py", line 69, in clear
    if self._data_handler.haskey(session_id):
AttributeError: 'dict' object has no attribute 'haskey'
2018-03-11 18:33:00 web.py[line:2064] ERROR 500 GET /cms/logout (192.168.1.123) 3.72ms
2018-03-11 18:33:21 web.py[line:1591] ERROR Uncaught exception GET /cms/logout (192.168.1.123)
HTTPServerRequest(protocol='http', host='192.168.1.182:8010', method='GET', uri='/cms/logout', version='HTTP/1.1', remote_ip='192.168.1.123', headers={'Accept-Language': 'zh-CN,zh;q=0.9', 'Accept-Encoding': 'gzip, deflate', 'Host': '192.168.1.182:8010', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.119 Safari/537.36', 'Dnt': '1', 'Connection': 'keep-alive', 'Cookie': 'sessionID=0UiAHYb3eCXKjbIs-KeOqnlnMjMIAJceQiV1f7g2; msid=e1dHKjhzacG6tIU-MdqFzFCxpY1En-tmMdW7N3jp; _xsrf=2|f7030538|7d8778473a8e1a5cdd4289802e49ec97|1520749458; user="2|1:0|10:1520764376|4:user|16:aHlwQHFxLmNvbQ==|499397512cabc459b2aa4af63885c555c76c0213c04c764a8a8fe1d9ff3e6ff7"', 'Cache-Control': 'max-age=0', 'Upgrade-Insecure-Requests': '1'})
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1512, in _execute
    result = yield result
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 292, in wrapper
    result = func(*args, **kwargs)
  File "/home/xiaodong/gittemp/healer_blogs_web/handler/cms/cms_handlers.py", line 151, in get
    self.clear_session_obj()
  File "build/bdist.linux-x86_64/egg/tornado_session/session.py", line 259, in clear_session_obj
    self.session_handler.driver.clear(session_id)
  File "build/bdist.linux-x86_64/egg/tornado_session/memorysession.py", line 69, in clear
    if self._data_handler.haskey(session_id):
AttributeError: 'dict' object has no attribute 'haskey'
2018-03-11 18:33:21 web.py[line:2064] ERROR 500 GET /cms/logout (192.168.1.123) 2.16ms
2018-03-11 18:33:23 web.py[line:1591] ERROR Uncaught exception GET /cms/logout (192.168.1.123)
HTTPServerRequest(protocol='http', host='192.168.1.182:8010', method='GET', uri='/cms/logout', version='HTTP/1.1', remote_ip='192.168.1.123', headers={'Accept-Language': 'zh-CN,zh;q=0.9', 'Accept-Encoding': 'gzip, deflate', 'Host': '192.168.1.182:8010', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.119 Safari/537.36', 'Dnt': '1', 'Connection': 'keep-alive', 'Cookie': 'sessionID=0UiAHYb3eCXKjbIs-KeOqnlnMjMIAJceQiV1f7g2; msid=e1dHKjhzacG6tIU-MdqFzFCxpY1En-tmMdW7N3jp; _xsrf=2|f7030538|7d8778473a8e1a5cdd4289802e49ec97|1520749458; user="2|1:0|10:1520764376|4:user|16:aHlwQHFxLmNvbQ==|499397512cabc459b2aa4af63885c555c76c0213c04c764a8a8fe1d9ff3e6ff7"', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache', 'Upgrade-Insecure-Requests': '1'})
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1512, in _execute
    result = yield result
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 292, in wrapper
    result = func(*args, **kwargs)
  File "/home/xiaodong/gittemp/healer_blogs_web/handler/cms/cms_handlers.py", line 151, in get
    self.clear_session_obj()
  File "build/bdist.linux-x86_64/egg/tornado_session/session.py", line 259, in clear_session_obj
    self.session_handler.driver.clear(session_id)
  File "build/bdist.linux-x86_64/egg/tornado_session/memorysession.py", line 69, in clear
    if self._data_handler.haskey(session_id):
AttributeError: 'dict' object has no attribute 'haskey'
2018-03-11 18:33:23 web.py[line:2064] ERROR 500 GET /cms/logout (192.168.1.123) 2.79ms
2018-03-11 18:36:06 web.py[line:2064] WARNING 404 GET /login?next=%2Fcms%2Flogout (192.168.1.123) 1.61ms
2018-03-11 18:36:12 web.py[line:2064] WARNING 404 GET /login?next=%2Fcms%2F (192.168.1.123) 0.68ms
2018-03-11 18:36:27 web.py[line:2064] WARNING 404 GET /login?next=%2Fcms%2F (192.168.1.123) 1.89ms
2018-03-11 18:36:54 web.py[line:2064] WARNING 404 GET /static/css/bootstrap.min.css.map (192.168.1.123) 5.50ms
2018-03-11 18:36:59 web.py[line:2064] WARNING 404 GET /login?next=%2Fcms%2Flogout (192.168.1.123) 2.44ms
2018-03-11 18:38:00 web.py[line:2064] WARNING 404 GET /static/css/bootstrap.min.css.map (192.168.1.123) 10.96ms
2018-03-11 18:38:05 web.py[line:2064] WARNING 404 GET /static/css/bootstrap.min.css.map (192.168.1.123) 2.07ms
2018-03-11 18:38:08 web.py[line:2064] WARNING 404 GET /login?next=%2Fcms%2Flogout (192.168.1.123) 2.05ms
2018-03-11 18:38:11 web.py[line:2064] WARNING 404 GET /login?next=%2Fcms%2F (192.168.1.123) 1.57ms
2018-03-11 18:39:31 web.py[line:2064] WARNING 404 GET /static/css/bootstrap.min.css.map (192.168.1.123) 4.46ms
